### ISSUE TITLE
[Bug]: Instance domain and postId are errors after changing

### ISSUE THREAD

**Issue by A5yncX** [rosnovsky/astro-mastodon#25]
When I was trying to insert a toot and changed your demo(`@rosnovsky@lounge.town:109860863149734322`)

such as `@AsyncX@mastodon.social:112054527697723909`, It's unable to work properly then.

PS: When I changed `username` in your demo, they also can run.(`@XXXXXXXX@lounge.town:109860863149734322`)

Here is the err code:
```
Cannot read properties of null (reading 'accountUrl')
at Heading (file:///Users/ax/ALL-IN/repositories/DG/node_modules/astro-mastodon/dist/components/Heading.js:6:51)
    at Ib (/Users/ax/ALL-IN/repositories/DG/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js:67:254)
    at Jb (/Users/ax/ALL-IN/repositories/DG/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js:76:98)
    at W (/Users/ax/ALL-IN/repositories/DG/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js:73:345)
    at Ib (/Users/ax/ALL-IN/repositories/DG/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js:68:145)
```

**Comment by rosnovsky** [comment]
@A5yncX thanks for reporting this, I'm looking into it now

**Comment by rosnovsky** [comment]
Fixed! Love the photo 😻 

The issue was that some instances (`mastodon.social` in this case) return empty `[display_name](https://docs.joinmastodon.org/entities/Account/#display_name)` field. It's not _strictly_ required, but I haven't seen it being empty previously.

![image](https://github.com/rosnovsky/astro-mastodon/assets/2508576/74862ee2-627a-4e93-b4a9-35ed1799bcdb)

**Comment by A5yncX** [comment]
Thank you! 😁
